### ISSUE TITLE
Código del curso

### ISSUE THREAD

**Issue by javimu** [dfreniche/ios-desde-cero#11]
En el primer episodio se comenta que el código estará en el repo de Github. Por favor, ¡podrías indicar donde? No lo encuentro. Gracias.

**Comment by dfreniche** [comment]
Hola!

si tienes git instalado lo más sencillo es clonar este repositorio con un `git clone https://github.com/dfreniche/ios-desde-cero`. Pero si no sabes qué es git no hay problema:
- puedes leer el código online en https://github.com/dfreniche/ios-desde-cero/tree/main/episodios 
- o bajarte un zip con todo el código como se explica en este vídeo: https://youtu.be/KzZcnBzI3OU

Añadiré instrucciones, ahora que me doy cuenta he supuesto que todo el mundo sabe usar git y no tiene por qué. 

Gracias por el feedback y comenta las dudas que te surjan!

**Comment by javimu** [comment]
Hola Diego.

He clonado el repositorio, y dentro de la carpeta episodios veo el MD de cada clase, pero dentro no está el código fuente  del video.

Quizás es una foto, y derivado de que yo no veo, no estoy viendo el código,, no lo sé.

En el vídeo Jonathan Chacón te te comenta que leas el código, pero claro, lógicamente eso es tedioso. Tras ese comentario, indicas que en el repositorio de Github pondrás también el código fuente de la clase. No sé si finalmente lo has hecho o no.

De cualquier modo, siguiendo lo que comentas en tu clase, he encontrado un manual de Apple Codding, donde he podido entender la parte de la declaración opcional.

Te agradezco mucho tu esfuerzo en este curso que estás haciendo. Te sigo en otros Podcast, y me he enterado tarde de que hacías este curso, estoy empezándolo ahora. Espero poder sacar tiempo para terminarlo.

Diego, de nuevo, muchas gracias por tu tiempo y esfuerzo.

Un fuerte abrazo.

**Comment by dfreniche** [comment]
Hola @javimu 

Por si aún te sirve, en el último stream estuve hablando de cómo usar el código, pero también lo he añadido en el [README](https://github.com/dfreniche/ios-desde-cero#c%C3%B3mo-uso-el-c%C3%B3digo-de-cada-episodio)

Espero que te sirva!

**Comment by javimu** [comment]
Hola Diego.

 

Muchas gracias.

 

Todo está perfecto. A partir de la sesión 002 si está el código. La sesión 0 y 1 no tiene código, de ahí mi confusión.

 

De nuevo muchas gracias.

 

Saludos.

 

 

 

De: Diego Freniche ***@***.***> 
Enviado el: jueves, 1 de septiembre de 2022 16:37
Para: dfreniche/ios-desde-cero ***@***.***>
CC: JaviMU ***@***.***>; Mention ***@***.***>
Asunto: Re: [dfreniche/ios-desde-cero] Código del curso (Issue #11)

 

Hola @javimu <https://github.com/javimu> 

Por si aún te sirve, en el último stream estuve hablando de cómo usar el código, pero también lo he añadido en el README <https://github.com/dfreniche/ios-desde-cero#c%C3%B3mo-uso-el-c%C3%B3digo-de-cada-episodio> 

Espero que te sirva!
