### ISSUE TITLE
Las áreas de xCode

### ISSUE THREAD

**Issue by TyflosAccessibleSoftware** [dfreniche/ios-desde-cero#2]
Estaría bien que enseñases las distintas zonas y herramientas de xCode y para qué sirven: la toolbar de arriba, la consola de depuración, el explorador de proyectos, etc

**Comment by dfreniche** [comment]
Excelente idea, ya que Xcode tiene muchas partes distintas. Las iremos viendo poco a poco, según las necesitemos, ya que "de golpe" puede ser traumático. Lo añado a la lista de temas.

Acepto y cierro este issue con 9a015624ebbe4a96ff0bccbf0c065f2456ad0184
