### ISSUE TITLE
Marcación de ámbitos

### ISSUE THREAD

**Issue by oliverjtowers** [dfreniche/ios-desde-cero#6]
Buenos días,

He comprobado que en tu Xcode al lado de los números te aparece una marcación en forma de barras grises que te indican los ámbitos (donde empiezan y acaban las llaves "{ }"). ¿Eso en qué parte del IDE se activa ?

Ejem:
https://clips.twitch.tv/OnerousPeacefulAdminOneHand-9Vj02eQJlGkfAK0u

Salu2.

**Comment by dfreniche** [comment]
Tienes que ir a Settings (Cmd + ,) y en la pestaña Text Editing cambiar Code Folding ribbon

![Screenshot 2022-04-22 at 13 26 55](https://user-images.githubusercontent.com/1008174/164706006-7c67d39d-3cd8-4027-b381-d796a62449a4.png)

**Comment by oliverjtowers** [comment]
Solucionado, muchas gracias!!
